### ISSUE TITLE
TTF or OTF files?

### ISSUE THREAD

**Issue by apjanke** [dadap/pIqaD-fonts#1]
Hi! I'd like to try your font. It was recommended to me [here](https://github.com/ryanoasis/nerd-fonts/issues/409#issuecomment-570455047).

I'm afraid I have no idea what to do with a `.bf` font file. I use macOS and Windows, where I know how to install `.ttf` and `.otf` fonts.

Any chance you could provide `.ttf`/`.otf` files, or instructions on how to transform your `.bf` file into those formats?

**Comment by gusbemacbe** [comment]
You can get the TTF from Releases: https://github.com/dadap/pIqaD-fonts/releases. Sorry for failing to forward you to direct download.

**Comment by apjanke** [comment]
Oh, that's what I need. Thank you! It didn't occur to me to look in the Releases section. Should've, though.
